plugins { id 'com.android.application' }
android { namespace 'com.heavyy.projectx'; compileSdk 35
 defaultConfig { applicationId 'com.heavyy.projectx'; minSdk 23; targetSdk 35; versionCode 7; versionName '5.1' }
 buildTypes { debug { applicationIdSuffix '.debug'; versionNameSuffix '-debug' }; release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
}
dependencies { implementation 'androidx.appcompat:appcompat:1.7.0'; implementation 'androidx.activity:activity:1.9.3'; implementation 'com.google.android.material:material:1.12.0' }
